#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
#---------------------------------------------------#
# HTTP 代理端口
# port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的透明代理服务器端口（重定向 TCP 和 TProxy UDP）
redir-port: 7892

# Linux 的透明代理服务器端口（TProxy TCP 和 TProxy UDP）
tproxy-port: 7893

# HTTP 和 SOCKS4(A)/SOCKS5 服务器在同一端口
mixed-port: 7890

# 本地 SOCKS5 / HTTP(S) 服务认证
#authentication:
# - "admin:@admin123"

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 仅在将allow-lan设置为true时适用
# #"*": 绑定所有IP地址
# #192.168.122.11: 绑定单个IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"
ipv6: true

# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
# mode: script

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# Clash 的 RESTful API
external-controller: ':9090'

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# http://127.0.0.1:9090/ui/#/
# external-ui: folder
# yacd面板：  https://github.com/haishanh/yacd
# Razord面板：http://clash.razord.top/#/proxies
# external-ui: dashboard

# RESTful API 的口令 (可选)
secret: "@admin123"

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true
  # interface-name: eth0 # 绑定接口名称

# fwmark on Linux only 
routing-mark : 0x162

# DNS 服务器和连接建立的静态主机（如 /etc/hosts）
# 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效
#hosts:
#  'www.baidu.com': 36.152.44.96

# DNS 服务器设置
dns:
  enable: true  # 是否启用dns
  listen: ':53' # dns监听端口
  ipv6: true
  enhanced-mode: redir-host # 模式：redir-host或fake-ip
  use-hosts: true # 查找主机并返回 IP 记录
  # 以下填写的 DNS 服务器将会被用来解析 DNS 服务的域名
  # 仅填写 DNS 服务器的 IP 地址
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
    - "[2400:3200::1]:53"
    - "[240C::6666]:53"
  # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号。
  # 所有 DNS 请求将会直接发送到服务器，不经过任何代理。
  # Clash 会使用最先获得的解析记录回复 DNS 请求
  nameserver:
    - 223.5.5.5
    - 223.6.6.6
    - "[2400:3200::1]:53"
    - "[240C::6666]:53"
    - https://dns.alidns.com/dns-query
  # 当 fallback 参数被配置时, DNS 请求将同时发送至上方 nameserver 列表和下方 fallback 列表中配置的所有 DNS 服务器.
  # 当解析得到的 IP 地址的地理位置不是 CN 时，clash 将会选用 fallback 中 DNS 服务器的解析结果。
  fallback:
    - 8.8.8.8
    - 8.4.4.4
    - 1.1.1.1
    - 1.0.0.1
    - "[2001:4860:4860::8888]:53"
    - "[2001:4860:4860::8844]:53"
    - "[2606:4700:4700::1111]:53"
    - "[2606:4700:4700::1001]:53"
    - https://jp-nrt.doh.sb/dns-query
    - https://hk-hkg.doh.sb/dns-query
    - https://sg-sin.doh.sb/dns-query
    - https://kr-sel.doh.sb/dns-query
    - https://doh.dns.sb/dns-query
  # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
  # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 true 且 IP 地址的地理位置为 CN 时，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 false, 如果解析结果不在 fallback-filter.ipcidr 范围内，
  # Clash 总会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 采取以上逻辑进行域名解析是为了对抗 DNS 投毒攻击。
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
  # 通过特定域名服务器查找域名
  nameserver-policy:
    'www.baidu.com': '223.5.5.5'

# 混合配置（mixin）
# 支持向所有配置文件中注入公共属性设置
mixin:
  dns:
    enable: true
    listen: ':53'
    enhanced-mode: redir-host
    use-hosts: true
    default-nameserver:
      - 223.5.5.5
      - 223.6.6.6
      - "[2400:3200::1]:53"
      - "[240C::6666]:53"
    nameserver:
      - 223.5.5.5
      - 223.6.6.6
      - "[2400:3200::1]:53"
      - "[240C::6666]:53"
      - https://dns.alidns.com/dns-query
    fallback:
      - 8.8.8.8
      - 8.4.4.4
      - 1.1.1.1
      - 1.0.0.1
      - "[2001:4860:4860::8888]:53"
      - "[2001:4860:4860::8844]:53"
      - "[2606:4700:4700::1111]:53"
      - "[2606:4700:4700::1001]:53"
      - https://jp-nrt.doh.sb/dns-query
      - https://hk-hkg.doh.sb/dns-query
      - https://sg-sin.doh.sb/dns-query
      - https://kr-sel.doh.sb/dns-query
      - https://doh.dns.sb/dns-query
    fallback-filter:
      geoip: true
      geoip-code: CN
      ipcidr:
        - 240.0.0.0/4
    # 通过特定域名服务器查找域名
    nameserver-policy:
      'www.baidu.com': '223.5.5.5'

cfw-latency-timeout: 3000
cfw-latency-url: http://www.gstatic.com/generate_204      
cfw-conn-break-strategy:
  proxy: none
  profile: true
  mode: false
cfw-proxies-order: default
